version: "3.7" #victor asked to update to 3.7 because of some issues with 3.8 he had

services:
  ci:
    build:
      context: ./webhook/
      dockerfile: Dockerfile
    image: webhook
    container_name: webhook
    restart: unless-stopped
    tty: true
    working_dir: /app
    ports:
      - "8086:8086"
    volumes:
      - ../:/app/data/
      - /var/run/docker.sock:/var/run/docker.sock
